### ISSUE TITLE
[ktx2] --automipmap does not work (at least with --bcmp)

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/KTX-Software#144] opened 2019-11-24 06:09 UTC
I'm trying to use toktx instead of basisu to produce a compressed 2D image with a full mipmap chain. Here's what happens if I run both tools with default arguments:

```
$ toktx --t2 --bcmp Material_20_baseColor.ktx Material_20_baseColor.png
$ basisu -file Material_20_baseColor.png
$ ls -la Material_20_baseColor.*
-rwxrwxrwx 1 zeux zeux  342411 Nov 24 11:34 Material_20_baseColor.basis
-rwxrwxrwx 1 zeux zeux  342552 Nov 24 11:37 Material_20_baseColor.ktx
-rwxrwxrwx 1 zeux zeux 3515875 Nov 24 11:32 Material_20_baseColor.png
```

This makes sense. The KTX file is slightly larger, presumably due to the larger header.
Now let's try to add -mipmap argument to basisu and --automipmap to toktx:

```
$ basisu -file Material_20_baseColor.png -mipmap
$ toktx --t2 --bcmp --automipmap Material_20_baseColor.ktx Material_20_baseColor.png
$ ls -la Material_20_baseColor.*
-rwxrwxrwx 1 zeux zeux  478834 Nov 24 11:38 Material_20_baseColor.basis
-rwxrwxrwx 1 zeux zeux  342552 Nov 24 11:38 Material_20_baseColor.ktx
-rwxrwxrwx 1 zeux zeux 3515875 Nov 24 11:32 Material_20_baseColor.png
```

Clearly basisu added a mipmap chain to the compressed file, but toktx simply ignored the argument.

**Comment by MarkCallow** [comment] 2019-11-24 06:52
`-automipmap` does not generate mipmaps. The documentation says:

```
        "  --automipmap A mipmap pyramid will be automatically generated when the KTX\n"
        "               file is loaded. This option is mutually exclusive with --levels\n"
        "               and --mipmap.\n"
```

The key here is "_when the KTX file is loaded_." I.e the pyramid is generated by OpenGL or Vulkan.

Generating a pyramid within toktx is something that needs to be added and something I want. For that I would call the option `--generatemipmap`. I'd be happy to accept a PR to add this function.

To create a mipmapped .ktx2 file with `toktx` now, you have to specify `--mipmap` and provide each of the images on the command line or by listing the file names in a file referenced with `@` on the command line. E.g.

```bash
toktx --mipmap --t2 out.ktx2 @mipfilelist.txt
```

Be aware that `basisu_tool` -mipmap option only really works for 1D or 2D images as it puts the mip levels immediately after the base image. When loading, e.g. array textures you need the images for each layer of the array of the same level together sequentially. This means we cannot simply use the `basisu_encoder` mipmap generation functionality.

Since `--automipmap` does work as intended, I'm going to close this. Please open another issue for adding mipmap generation functionality.

**Closed by MarkCallow** 2019-11-24 06:52 UTC
