### ISSUE TITLE
toktx inconsistent behaviour across different calls

### ISSUE THREAD

**Issue by tuket** [KhronosGroup/KTX-Software#449] opened 2021-07-20 09:47 UTC
I'm using toktx with the following command line:

```
.\toktx.exe --uastc --assign_oetf linear --mipmap "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.ktx" "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip0.png" "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip1.png" "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip2.png" "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip3.png" "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip4.png" "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip5.png" "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip6.png" "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip7.png" "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip8.png" "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip9.png" "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip10.png"
```

Most of the times it will give the following error, and doesn't generate any output:

```
toktx: "C:\Users\tuket\Pictures\albedo\amedey_piel_physics.mip1.png" is encoded with a different transfer function (OETF) than preceding files
```

Sometimes, it will successfully generate the output .ktx.

I'm not sure which should be the expected behaviour but at least it should be consistent; sounds like it might be using uninitialized memory.

```
> .\toktx.exe --version
toktx v4.0.0~6
```

**Comment by MarkCallow** [comment] 2021-07-27 07:43
Thanks for the report. This is a duplicate of issue #423.

**Closed by MarkCallow** 2021-07-27 07:43 UTC
Labels: duplicate
