### ISSUE TITLE
Specific file results in very bad compression results when mipmaps are enabled

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/KTX-Software#759] opened 2023-08-31 15:29 UTC
Related to
- https://github.com/donmccurdy/glTF-Transform/issues/1062

A specific file ends up with very bad quality after compression, but only if mipmaps are enabled.

This texture here: https://github.com/donmccurdy/glTF-Transform/files/12327580/watch.zip

Compression without mipmaps:
![image](https://user-images.githubusercontent.com/5083203/260237312-f11a2dd2-a754-4cbe-8d8f-911a7e4db8c3.png)

Compression with mipmaps:
![image](https://user-images.githubusercontent.com/5083203/260236959-f0093a39-6278-4343-8eee-6a8962b07370.png)

Compressing without mipmaps results in expected quality. This is the first time we're hitting a particular texture giving such results, however an outlier like this is quite problematic for the use of KTX in production pipelines.

**Comment by MarkCallow** [comment] 2023-09-01 05:27
Please list the command and options that is being used.

Images are compressed to ETC1S individually. BasisLZ is then applied to all levels, starting from the largest, using a global codebook from which previously seen runs of data may be reused.  It is therefore most unlikely that adding mipmaps could affect the quality of the base image. @hybridherbst are you sure the 2 images you posted here are displaying the same miplevel?

**Comment by hybridherbst** [comment] 2023-09-01 07:20
@MarkCallow I'm not sure if this displays the same mip level but I am sure that this is the mip level viewers like three.js and others choose when displaying the file. In the original zip I added glb files where the ktx2 textures have and have not mipmaps as per the commands below.

Command is pretty much "default options for a linear file" as far as I can tell:
```
toktx --genmipmap --bcmp --assign_oetf linear --assign_primaries none metallicRoughness.mips.ktx2 metallicRoughness.jpg
```
vs.
```
toktx --bcmp --assign_oetf linear --assign_primaries none metallicRoughness.ktx2 metallicRoughness.jpg
```

Here's the extracted textures again:
[metallicRoughness.zip](https://github.com/KhronosGroup/KTX-Software/files/12495416/metallicRoughness.zip)

**Comment by hybridherbst** [comment] 2023-09-01 07:37
I found a viewer that lets me take a closer look at the invidiual mip levels. It appears to me that for this particular file, mip levels feel lower resolution much faster than they should.

This is mip 4 when using --uastc:
<img width="694" alt="image" src="https://github.com/KhronosGroup/KTX-Software/assets/2693840/0734edd2-b23d-4008-82c3-1513fb5d10ee">

And this is mip 4 when using --bcmp:
<img width="692" alt="image" src="https://github.com/KhronosGroup/KTX-Software/assets/2693840/5b95c24f-7c3b-4638-abe5-84b747752c2a">

Mip 2 when using --uastc:
<img width="691" alt="image" src="https://github.com/KhronosGroup/KTX-Software/assets/2693840/a6874962-f792-45b1-963e-ef6cbe4e84ee">

Mip 2 when using --bcmp:
<img width="693" alt="image" src="https://github.com/KhronosGroup/KTX-Software/assets/2693840/a0ac1a04-a5f1-4f10-b90e-58c7e728015f">

Mip 0 also already looks "not great" but not that bad as the others. I understand there should be _some_ difference but not that strong. Is libktx calculating each mip level from the original texture, or is it calculating them from each other iteratively? In that case I think the latter may be going wrong.

**Comment by MarkCallow** [comment] 2023-09-01 13:15
I don't think there is anything unexpected here. Here is an image showing all the mip levels in an uncompressed version of the texture:

<img width="1392" alt="Screenshot 2023-09-01 at 21 46 34" src="https://github.com/KhronosGroup/KTX-Software/assets/2244683/d7ecd7f1-57c1-4e26-b302-3d00492ac5be">

Here is the image using UASTC. Virtually the same:

<img width="1392" alt="Screenshot 2023-09-01 at 21 46 56" src="https://github.com/KhronosGroup/KTX-Software/assets/2244683/d3bf9c07-e8b2-4291-b30f-480f7283959a">

And here is the image using ETC1S/Basis-LZ:

<img width="1344" alt="Screenshot 2023-09-01 at 21 47 03" src="https://github.com/KhronosGroup/KTX-Software/assets/2244683/efebb55e-f6d9-4f3e-bb2b-0dc7a7830e28">

With ETC1S the smaller mip levels are noticeably worse but as the source data is (a) not color data (which is what ETC is designed for) and (b) has already been compressed with JPEG, the degradation is expected.

**Comment by hybridherbst** [comment] 2023-09-01 21:04
I disagree. Almost identical textures don't result in the same level of quality loss; this is the first time we're seeing that level of degradation over thousands of processed textures. And yes, we're using ETC also for data textures in some cases where file size is more important, and so far that has _never_ resulted in such bad compression.

**Comment by MarkCallow** [comment] 2023-09-02 06:48
> Is libktx calculating each mip level from the original texture, or is it calculating them from each other iteratively? In that case I think the latter may be going wrong.

Each level is calculated from the original texture. The screen shot I posted of the uncompressed texture shows the images that will be input to the BasisU encoders.

> I disagree. Almost identical textures don't result in the same level of quality loss; this is the first time we're seeing that level of degradation over thousands of processed textures. And yes, we're using ETC also for data textures in some cases where file size is more important, and so far that has never resulted in such bad compression.

@hybridherbst have you made similar metallic roughness textures using only the default ETC1S/Basis-LZ parameters and not had this problem? If so,

1. what is different between ones without the problem and this one?
2. please provide an example that does not have this problem.
3. please try the interactive [glTF-Compressor Tool](https://github.khronos.org/glTF-Compressor-Release/) and see if you can get better results for this texture by fine tuning the compression parameters.

If something is going on it is happening within the BasisU ETC1S encoder and is outside my expertise. Therefore I must consult @richgel999. Sorry to bother you Rich but please give us your opinion about this. Follow this link [metallicRoughness.zip](https://github.com/KhronosGroup/KTX-Software/files/12495416/metallicRoughness.zip) for the original jpg. The link provided in the initial comment only has .glb files.

**Comment by MarkCallow** [comment] 2023-09-08 05:00
@hybridherbst have you found a similar metallic-roughness texture that does not display this issue? Have you tried the interactive tool?

**Comment by MarkCallow** [comment] 2023-11-28 03:24
The source file `metallicRoughness.jpg` is sRGB which you are overriding with `--assign_oetf linear` thereby screwing up mipmap generation. If you remove `--assign_oetf linear` the jaggies will disappear. Never, ever use `--assign_oetf linear` unless you are absolutely certain that the metadata in the source file is wrong.

**Closed by MarkCallow** 2023-11-28 03:24 UTC

**Comment by donmccurdy** [comment] 2024-02-18 14:18
> you are overriding with --assign_oetf linear thereby causing the mipmap generator to filter in sRGB space

Did you mean "to filter in linear space" here?

Data textures (like metallic/roughness) are always linear in glTF. They cannot be sRGB, and the glTF spec is strict about saying that metadata in the file MUST be ignored, because the metadata is so often wrong... Tools processing glTF files should always use `--assign_oetf` as a result. 

If the source file really has sRGB-encoded the metallic roughness data, though, data loss is baked into the source file.

**Comment by hybridherbst** [comment] 2024-02-18 15:35
We're using etc1s for data textures fine, still besides this one singular texture which produces so much worse results.
 
I'm not sure I understand both of your comments above – seems like Mark is saying "never use `--assign_oetf linear`" while gltf-transform always uses `--assign_oetf linear` for, well, linear data. What is the correct approach here?

**Comment by hybridherbst** [comment] 2024-02-18 15:35
We're using etc1s for data textures fine, still besides this one singular texture which produces so much worse results.
 
I'm not sure I understand both of your comments above – seems like Mark is saying "never use `--assign_oetf linear`" while gltf-transform always uses `--assign_oetf linear` for, well, linear data. What is the correct approach here?

**Comment by donmccurdy** [comment] 2024-02-18 16:19
I don't think there's any other choice glTF Transform could make but `--assign_oetf linear`. It's very rare that metal/rough data is actually sRGB-encoded (and always incorrect), but very common that the metadata is wrong. I can't tell if that was the cause here, it sounds plausible... but it's hard to tell with metal/rough data. 

Certainly unfortunate that image metadata is such a mess though. :/

**Comment by MarkCallow** [comment] 2024-02-19 03:26
> Did you mean "to filter in linear space" here?

Yes I meant filter in linear space. The data, according to the file metadata, is sRGB and when I removed the `-assign-oetf linear` from the command I did not see the excessive jaggies in the resulting texture. This suggests the file metadata is correct. Therefore if the source file is intended for metallic/roughness or other data use, it is incorrect and that is where the problem lies.

@donmccurdy glTF-Transform should issue a warning if someone tries to use an image whose metadata says sRGB for data use. Image tools these days generally set the metadata correctly so such a mismatch suggests a cockpit error when producing the image.

> What is the correct approach here?

Make sure the source image is linear.

**Comment by MarkCallow** [comment] 2024-02-19 08:12
> I don't think there's any other choice glTF Transform could make but --assign_oetf linear

Note that if you specify a UNORM format to `--format` `ktx create` will convert the input from sRGB to linear (if the metadata indicates its sRGB). Mipmaps will first be correctly generated by decoding the sRGB data before filtering and re-encoding before the final conversion to linear takes place (these are separate steps within the application). If you force `--assign-oetf linear` then not only are the mipmaps screwed up because the encoded data was filtered but sRGB data is then uploaded unchanged to the UNORM texture so when sampled in the the shader will receive sRGB encoded data.

As I wrote earlier you should be really sure the metadata is wrong before forcing linear. @donmccurdy do you have any evidence that the metadata is wrong for reasons other than cockpit error?

**Comment by donmccurdy** [comment] 2024-02-19 17:44
I have no evidence either way for the specific texture in this thread.

But in the broader 3D modeling ecosystem, I would not describe the problem as cockpit error. These decisions are being made at lower levels of software abstraction than most users understand — they export a model from Substance Painter, Maya, 3DS Max, or Blender, with textures embedded. They do not know which texture uses which color space (or lack thereof), and they probably don't have control over that choice even if they did.

For a quick test, I opened two examples from the glTF Sample Models repository — these are simply the first two models I opened, I did not have to go looking.

Mosquito In Amber:

| role | metadata color space | correct |
|------|----------------------|---------|
| baseColor | | | 
| baseColor | | |

**Comment by donmccurdy** [comment] 2024-02-19 18:01
@MarkCallow I have no evidence either way for the specific texture in this thread. It could certainly be user error!

But in the broader 3D modeling ecosystem, I would not describe the problem as one of user error. These decisions are being made at lower levels of software abstraction than most users understand or control — they export a model from Substance Painter, Maya, 3DS Max, or Blender, with 5-10 textures embedded. They do not know which texture uses which color space, and they probably don't have control over that choice even if they do understand it.

For a quick test, I opened two examples from the [glTF Sample Models](https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0) repository. These are simply the first two samples I opened — I did not have to go digging.

**Mosquito In Amber:**

| role | profile in metadata | valid |
|------|----------------------|---------|
| baseColor | sRGB | ✅ | 
| metallicRoughness | sRGB | ❌ | 
| normal | - | ✅ | 
| baseColor | sRGB | ✅ | 
| normal | sRGB | ❌ |

**Sheen Chair:**

| role | profile in metadata | valid |
|------|----------------------|---------|
| baseColor | - | ❌ | 
| normal | - | ✅ |
| baseColor | - | ❌ |
| occlusion | - | ✅ |
| baseColor | - | ❌ |
| metallicRoughness | sRGB | ❌ | 
| metallicRoughness | - | ✅ | 

I agree that "image tools these days generally set the metadata correctly", but only in the context of tools for opening and editing one texture at a time. Within the context of a larger 3D art workflow with many models and textures, there are "weak links" more often than not. For three.js, the web platform does not even give us the ability to read the color space of a JPEG or PNG texture (KTX2 is an exception) without duplicating the texture in memory.

I'd be glad to see the glTF Validator, glTF Transform, and other tools flag the issue more clearly. Perhaps we can improve the state of the 3D ecosystem. But it's a problem that long predates glTF, and I consider the image metadata to be mostly useless today, outside of very carefully controlled workflows.

**Comment by MarkCallow** [comment] 2024-02-20 00:13
@donmccurdy there is a difference between the metadata being wrong or non-existent and the colorspace of the source being inappropriate for the task. `--assign-oetf` is the right choice in the first case. Letting `ktx create` to do its job and convert the sRGB input to linear is the right choice in the second case. It will do this when the selected VkFormat is a UNORM format. Forcing linear leads to the issue in this bug. There will still be artifacts from having used an inappropriate encoding on the source file due to values that are lost during the initial encoding but far less than you will get from treating sRGB data as linear.

**Comment by donmccurdy** [comment] 2024-02-20 01:07
@MarkCallow In my experience the second case — data using an inappropriate colorspace with correct metadata — is rare. It's overwhelmingly more common that the metadata is wrong. Easily a 100:1 ratio. Perhaps this ticket represents an exception, but I can't justifiably change the default behavior based on that.

It doesn't seem that there's a general solution here, at the level of either KTX Software or glTF Transform. As you said above, the texture data must be linear.

**Comment by MarkCallow** [comment] 2024-02-20 02:17
> In my experience the second case — data using an inappropriate colorspace with correct metadata — is rare. It's overwhelmingly more common that the metadata is wrong.

@donmccurdy how do you know this? My experience with image editing tools is that encoding the data and setting metadata tend to go together when writing a file.

In my previous comment I should have noted that a better choice for the second case is `--convert-oetf linear`. With this the data is converted to linear before mipmap generation, saving the time that decoding and encoding takes during that process.

**Comment by MarkCallow** [comment] 2024-02-22 11:52
> @donmccurdy how do you know this?

Pinging again.

For example in the following case
> metallicRoughness 	sRGB 	❌

how do you know the metadata is wrong vs. the file being inadvertently encoded into sRGB?

I think it is basically a guess in which case glTF-Compressor should warn the user that either the metadata is wrong or the wrong encoding has been used. It should have an option or options for the user to indicate which is the case: --assign-oetf for the first and --convert -oetf for the second.

**Comment by donmccurdy** [comment] 2024-02-23 01:04
> how do you know this? My experience with image editing tools is that encoding the data and setting metadata tend to go together when writing a file.

This is simply my experience with PBR materials and their associated textures. I agree that modern "image editing tools" are pretty good about color spaces. But 3D art pipelines are more complicated and less consistent. In particular — I think the distinction between "sRGB color" and "non-color data" is not consistently represented in metadata. Metadata for wide gamut colorspaces like "Display P3" or "Rec. 2020" is less likely to be a side effect of broken workflows, and is therefore more reliable when present.

**Comment by MarkCallow** [comment] 2024-02-23 02:29
| I think the distinction between "sRGB color" and "non-color data" is not consistently represented in metadata.

Again I ask how can you tell if the metadata contradicts what's actually in the file or if the non-color data has been incorrectly (as in "it has but should not have been") encoded into sRGB.

Is there any image metadata that describes a distinction between color and non-color data? Metadata offering a choice between linear and sRGB does not. The latter simply says the input data has been encoded into a non-linear space.

I still think glTF-Compressor should inform the user and provide them the opportunity to guide it to a resolution instead of deciding the meta always contradicts the data that is actually in the file. That can lead to much worse results than decoding the sRGB data, if that is what it is, and using that.

**Comment by donmccurdy** [comment] 2024-02-23 03:33
> Again I ask how can you tell if the metadata contradicts what's actually in the file ...

I cannot look at a JPG containing metal/rough data, annotated as "sRGB", and tell you with confidence whether the metadata is wrong, or the actual choice of encoding is wrong. Other than a probabilistic expectation that it's usually the metadata. Is that what you're asking? 

> Is there any image metadata that describes a distinction between color and non-color data?

None that I'm aware of. Omission of an ICC profile perhaps, but I suspect many tools will simply interpret that as "sRGB".

> I still think glTF-Compressor should inform the user and ...

Ok — I have no particular opinion on what the glTF Compressor should do. I'd certainly be supportive of getting the glTF Validator to report inconsistent image color space metadata.
