### ISSUE TITLE
When compiling under Windows, it prompts unix2dos: command not found.

### ISSUE THREAD

**Issue by jimwang118** [KhronosGroup/KTX-Software#834] opened 2024-01-04 03:05 UTC
I updated `ktx` in `vcpkg` and installed it under Windows after updating the version. The following error occurred: `unix2dos: command not found`.
The installation was successful after I deleted all commands related to unix2dos.

**Comment by MarkCallow** [comment] 2024-01-05 09:29
`unix2dos` has been required for a very long time. What has changed in your set up that it is now an issue? On my Windows system I have 2 instances: one in GitForWindows, which also provides the Bash shell the build uses, and one in the Strawberry Perl installation.

It is only needed when rebuilding some source files that are generated from `vulkan_core.h` after a `vulkan_core.h` update. Such updates are rare so deleting the commands in the vcpkg version will not be an issue. Unfortunately cmake likes to run these commands for each build even though there has been no update to the dependencies. If it wasn't for this, you would never have noticed the existence of the commands that use unix2dos.

There are 2 problems that I'd like to fix but I've not been able to determine the causes in the time I've had available for investigation.

1. Why does cmake want to keep rerunning these build commands?
2. Why does Perl on Windows like to write Unix line endings? That is why we are using unix2dos. Perhaps the issue is fixed in recent versions of Perl.

**Comment by jimwang118** [comment] 2024-01-09 06:08
When installing port ktx in vcpkg, use an older version of msys, delete the old version of msys downloaded in the port, and use the msys automatically downloaded by vcpkg to install normally.

**Closed** 2024-01-19 01:21 UTC

**Comment by jimwang118** [comment] 2024-01-19 01:51
> When was it removed? It is still in Git for Windows which is based on msys.
> 
> Regardless, I have put the targets that were using it behind a config option that is off by default and also stopped using `unix2dos` in those targets.

There is no dos2unix command in the msys I downloaded. I added the download of dos2unix package and the problem was solved.

**Comment by MarkCallow** [comment] 2024-01-19 02:07
Thanks for the info @jimwang118. Now the PR has landed, you no longer need `unix2dos`.
