### ISSUE TITLE
Release --version differences across os's

### ISSUE THREAD

**Issue by dbuck** [KhronosGroup/KTX-Software#467] opened 2021-08-04 21:05 UTC
While debugging an issue with gltf-pipeline ([Related issue](https://github.com/donmccurdy/glTF-Transform/issues/319)), I noted that the versions returned from the build on osx / linux differ. Osx returns version strings from older betas, even if installed from the latest package, linux returns strings which are not valid semver

OSX:
From the install of v4 release for osx from the [4.0.0-Darwin.pkg installer](https://github.com/KhronosGroup/KTX-Software/releases/download/v4.0.0/KTX-Software-4.0.0-Darwin.pkg)
```
% ktx2check --version
ktx2check v4.0.0~13
% ktx2ktx2 --version
ktx2ktx2 v4.0.0-beta6~6
% ktxinfo --version
ktxinfo v4.0.0-beta6~6
% ktxsc --version
ktxsc v4.0.0-beta6~6
% toktx --version
toktx v4.0.0~6
```

Linux:
From the install of v4 release for linux from the [Software-4.0.0-Linux.tar](https://github.com/KhronosGroup/KTX-Software/releases/download/v4.0.0/KTX-Software-4.0.0-Linux.tar.bz2)

```
# ktx2check --version
ktx2check v4.0
# ktx2ktx2 --version
ktx2ktx2 v4.0
# ktxinfo --version
ktxinfo v4.0
# ktxsc --version
ktxsc v4.0
# toktx --version
toktx v4.0
```

**Comment by MarkCallow** [comment] 2021-08-04 23:27
The format of the OSX version strings is as intended.  It is from `git describe` and allows identification of the commit at which the software was built. It is extremely annoying that semver and git describe are not compatible. semver needs to allow additional separators between the version and "build metadata". We'll have to look into why the "-beta6" is in there.

The version in the Linux package is incorrect.

**Comment by dbuck** [comment] 2021-08-04 23:39
Thanks Mark, I did see that discussion in the PR in gltf-transform repo.

Maybe I'm misunderstanding, but it sounds like the OSX .pkg downloadable from the v4.0.0 tag in this repo, has --version strings that point to a commit 6 commits further along than the tag from which it is being downloaded?

**Comment by MarkCallow** [comment] 2021-08-19 06:30
> ktxinfo v4.0.0-beta6~6

> Maybe I'm misunderstanding, but it sounds like the OSX .pkg downloadable from the v4.0.0 tag in this repo, has --version strings that point to a commit 6 commits further along than the tag from which it is being downloaded?

You are, unless I am misunderstand the direction you mean by "further along". Note the "~". That is commits before not after. `git describe` uses "-" for commits after. Frankly they are much too easily confused. It would be better if `git describe` used something other than "-".

The example above says that the latest commit to affect ktxinfo was 6 commits *before* the `v4.0.0-beta6` tag. No changes were made between then and the v4.0.0 tag. This is correct but confusing. You can pass this, and any other, version string to `git commit` to checkout the exact commit. I will modify the script that generates the version strings to prioritize full release tags over rc tags over beta tags. After the change, if I were to rebuild the package at v4.0.0, the version string would be `v4.0.0-16` 16 commits before v4.0.0 rather than 6 commits before `v4.0.0-beta6`.

Looking into the Linux version number issue.

**Comment by MarkCallow** [comment] 2021-08-19 14:01
Building current master on Linux using the same script as is used by CI to produce the installers, I am unable to reproduce the incorrect version you saw, @dbuck.  I looked at both the .tar and .deb installers. I don't recall any fixes in this area since v4.0.0. Perhaps the problem only occurs when built in the CI environment. Next time I make a draft release, I will check.

**Comment by MarkCallow** [comment] 2021-08-20 01:26
The only way that `mkversion` could generate the version "v4.0" is if there is no .git directory or file in the source tree where it is running. I will look closely at the .yml file that controls the CI build.

**Comment by MarkCallow** [comment] 2021-08-20 06:15
I temporarily made the CI build print out information about versions in the apps it is building. The versions are correct. It looks like the problem leading to "v4.0" versions, whatever it was, has been fixed. I am going to close this after merging the fix for the confusing version numbers described above. I will definitely check the draft installer when we get to that stage in our next release.

**Closed** 2021-08-24 01:32 UTC
