### ISSUE TITLE
Windows installer fails to update PATH

### ISSUE THREAD

**Issue by matthew-rister** [KhronosGroup/KTX-Software#789] opened 2023-10-20 21:45 UTC
Installation of [v4.3.0-alpha3](https://github.com/KhronosGroup/KTX-Software/releases/tag/v4.3.0-alpha3) on Windows fails with the warning "Warning! PATH too long installer unable to modify PATH!" despite installing to C:\Program Files\KTX-Software\bin which is well below the 256 character limit on Windows.

**Comment by MarkCallow** [comment] 2023-10-21 05:09
Duplicate of, e.g., #675.

Fixed in main. Not yet released. Issue is only secondarily related to the length of the path to the installation.

**Closed by MarkCallow** 2023-10-21 05:09 UTC
Labels: duplicate
