### ISSUE TITLE
ERROR: Basis supercompression global data has incorrect size.

### ISSUE THREAD

**Issue by CITIZENDOT** [KhronosGroup/KTX-Software#705] opened 2023-05-20 08:19 UTC
I'm trying to compress multiple JPEG textures into one KTX2 file.

```
toktx --layers 13 --bcmp texture.ktx2 export_00000.jpg export_00001.jpg export_00002.jpg export_00003.jpg export_00004.jpg export_00005.jpg export_00006.jpg export_00007.jpg export_00008.jpg export_00009.jpg export_00010.jpg export_00011.jpg export_00012.jpg
```

I got this error with `ktx2check`.
```
❯ ktx2check texture.ktx2
Issues in: texture.ktx2
    ERROR: Basis supercompression global data has incorrect size.
```

I also got transcoding error with Three.js ktx2Loader. What am I doing wrong?

**Comment by MarkCallow** [comment] 2023-05-22 05:07
I cannot reproduce this. What version of `toktx` are you using? Are there any messages from `toktx`?

**Comment by CITIZENDOT** [comment] 2023-05-22 05:09
`toktx v4.0.0~6`. There is no output from `toktx`.

**Comment by MarkCallow** [comment] 2023-05-29 05:29
That is a very old version of `toktx`. Please try the current release or that at the tip of the `main` branch.

**Comment by MarkCallow** [comment] 2023-06-14 08:45
Closing as I am near certain this is no longer an issue.  Please reopen, if this is still an issue for you in the latest version.

I fixed issues around array texture creation some time ago.

**Closed by MarkCallow** 2023-06-14 08:45 UTC
